### PR TITLE
Closes #2

### LINKED ISSUE #2: Handing of diagnostics output more than cmdheight...
Hi,

First of all great plugin ! I came from vim-lsp which does diagnostic echo natively but couldn't find a good way in neovim until I stumble upon this.

Question is that if the diagnostics is more than `cmdheight`, it seems to pause the editor :

image

Here in this case whenever I land on the line, the "Press ENTER or type command to continue"  will show which is kind of annoying. Anyway to fix this?

### PR DESCRIPTION
**Pull request by seblyng**
@kting28

I am pretty sure this will fix your problem. I changed the logic to check the length per message to see if it should be truncated or not.

Could you test this to confirm that this fixes the problem?😅

### CODE REVIEW

**Comment by kting28** [comment]
Thanks for the fix. I think `cmdheight=2` works for different widths and I see it sometimes contact them to 1 line. But if cmdheight=1, it still spills to the 2nd line when it combines the 2 lines.

image

**Comment by seblyng** [comment]
Ah yes of course. I see where the problem is. Give me a few minutes and I will fix it!

**Comment by seblyng** [comment]
@kting28 Problem was that I didn't return early from the loop and just kept on going. Now it should work!

**Comment by kting28** [comment]
awesome works ! tested a few other cases of multiple diagnostic lines , different heights etc. all works. Ship it :)

**Comment by seblyng** [comment]
@kting28 I just changed the name of the branch since I had a typo in the name, so I'll open another PR and merge that. I think that it is good to go. If you experience any more issues, please open an issue to let me know!

**Pull request closed without merging**
